version: '3.8'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"  # Open port 9000 internally for communication with other containers

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    expose:
      - "5252"  # Open port 5252 internally for communication with other containers

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"  # Map container's port 80 to the host machine's port 80
    depends_on:
      - front-end
      - back-end
